/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Guido' at '3/12/16 11:14' with Gradle 3.2.1
 *
 * @author Guido, @date 3/12/16 11:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
